### ISSUE TITLE
Evaluate canvas component readiness from geppetto-meta

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#11]
The task is aimed to create a proof of concept using the latest geppetto-meta and the data provided by the client (https://drive.google.com/drive/folders/1EMiTLErFaV2CozisPtYpCv56p-U_5Ys0?usp=sharing there are different folders with many obj inside, does not really matter which data you want to use, feel free to pick from neurons or synapses).

The requirements are:
- use flexlayout since we will have to wrap all the canvas components and manage each of them.
- instantiate at least 3 canvases/3d viewers, report on responsiveness and eventual additional fixes required for the canvas.

Plus:
- try to instantiate as many 3d viewers as possible in relation to the responsiveness, define the same scene displayed in all of them (same objs list) just to roughly have an idea of what the limit could be.

**Comment by afonsobspinto** [comment]
- Use neurons and synapses (bigger the size the better)
- Zoom, rotation, selection handler

**Comment by afonsobspinto** [comment]
This is the latest:
![image](https://user-images.githubusercontent.com/19196034/118282851-a03feb80-b4c6-11eb-9fab-08bb79527a75.png)

- [ ] Fix movement on the canvas (only works after clicking on the controls, don't really understand why yet)
- [ ] Fix resizing, canvas only resizes after a click on it, meanwhile, it looks like the following:
![image](https://user-images.githubusercontent.com/19196034/118283043-d8dfc500-b4c6-11eb-9b8d-945a6f7ec38f.png)
- [ ] Add obj instead of cube

**Comment by afonsobspinto** [comment]
One obj file (SketchVolumeViewer_RIH_RIH_1_1_0000.obj -> 36,7mb)
Three Canvas
![image](https://user-images.githubusercontent.com/19196034/118519272-e0a2a200-b730-11eb-8464-3616d4df7cc0.png)

**Comment by afonsobspinto** [comment]
20 obj files
3 Canvas:

![image](https://user-images.githubusercontent.com/19196034/118523233-da162980-b734-11eb-9d70-8efe9b1cecb9.png)

**Comment by afonsobspinto** [comment]
10 obj files
3 canvas
![image](https://user-images.githubusercontent.com/19196034/118523460-0fbb1280-b735-11eb-8d5b-2689e95521fe.png)

**Comment by afonsobspinto** [comment]
The mean size of the Yale mean files is 14.37mb

**Comment by afonsobspinto** [comment]
Using the smallest obj file availabe (0.0462mb) -> SketchVolumeViewer_SABD_SABD_1_1_0000.obj

1 obj file
3 Canvas
(0.0462 mb per canvas)
~60fps

![image](https://user-images.githubusercontent.com/19196034/118529241-367c4780-b73b-11eb-9730-cdc3b78163f4.png)

___________________________________________________________________________________________________

10 obj files
3 Canvas
(0.42 mb per canvas)
~60fps

![image](https://user-images.githubusercontent.com/19196034/118529688-b3a7bc80-b73b-11eb-80a2-ade01ebe5b22.png)

________________________________________________________________________________________________

20 obj files
3 Canvas
(4.2 mb per canvas)
~60fps
![image](https://user-images.githubusercontent.com/19196034/118529533-84914b00-b73b-11eb-8147-5a297dd12b5f.png)

**Comment by afonsobspinto** [comment]
In my experiences with 3 canvas, when we have more than 100mb per canvas we start having less than 60 fps

**Comment by afonsobspinto** [comment]
1 canvas
25 obj files
360mb 
~45fps
![image](https://user-images.githubusercontent.com/19196034/118628279-5f94ea80-b7c4-11eb-9b50-cd39b918a694.png)

**Comment by afonsobspinto** [comment]
Converting SketchVolumeViewer_SAAVR_SAAVR_1_1_0000.obj (14.4mb) to SketchVolumeViewer_SAAVR_SAAVR_1_1_0000.drc (0.141mb) improved the visualization. Here's how much it changed:


10 obj files
3 Canvas
~55fps
![image](https://user-images.githubusercontent.com/19196034/118658228-194f8380-b7e4-11eb-82ce-83d16f75f1ea.png)
_____________________________________________________________________________________________________

20 obj files
3 Canvas
~45fps
![image](https://user-images.githubusercontent.com/19196034/118658432-469c3180-b7e4-11eb-8215-470d80061a30.png)

**Comment by afonsobspinto** [comment]
gtlf conversion:

Converting SketchVolumeViewer_SAAVR_SAAVR_1_1_0000.obj (14.4mb) to SketchVolumeViewer_SAAVR_SAAVR_1_1_0000.gtlf (9.4mb) improved the visualization as well. 

Here's how much it changed:

10 obj files
3 Canvas
(94 mb per canvas)
~60fps
![image](https://user-images.githubusercontent.com/19196034/118663033-62093b80-b7e8-11eb-9381-c63f0a97748a.png)
_____________________________________________________________________________________________________

20 obj files
3 Canvas
(188 mb per canvas)
~45fps
![image](https://user-images.githubusercontent.com/19196034/118662863-3e45f580-b7e8-11eb-8341-24e61f24bcf7.png)

**Comment by afonsobspinto** [comment]
Is worth mentioning that the fps counter present in all the threads doesn't mean that we have a constant X amount of fps but rather that the scene render loop tends to X fps. With movement, we can have momentaneous drops of fps followed by the increase back to X fps

**Comment by afonsobspinto** [comment]
60 SketchVolumeViewer_SAAVR_SAAVR_1_1_0000.gltf meshes with only threejs scene (no geppetto canvas)

Feels slightly better, probably because is just 1 canvas, but still renders around 45 frames per seconds (same as with geppetto canvas with the same amount of meshes split by the 3 canvas)
![image](https://user-images.githubusercontent.com/19196034/119341261-74252700-bc8b-11eb-9497-21e5e1cb1621.png)

**Comment by afonsobspinto** [comment]
Tests performed still with the current canvas which uses an infinite animation loop instead of rendering on-demand (PR still pending)
The fps values shouldn't be affected with new PR (it will only decrease the cpu usage on non-interaction moments)

Conditions of the test:
- Neuron RIH_RIH (heavist in the original files)
- 1 object per canvas


Original file (36.7mb):
-  35 fps 
![image](https://user-images.githubusercontent.com/19196034/131497340-dd34fb5d-1ee5-461d-bd8e-fbed0d3ef816.png)

0.1 fixing (4.0mb):
- 60 fps
![image](https://user-images.githubusercontent.com/19196034/131496668-43479ec7-e1d0-430c-a6d4-8e2ab06d2515.png)


0.05 fixing (1.6mb):
- 60 fps
![image](https://user-images.githubusercontent.com/19196034/131496992-3563a5a5-441e-4b45-9468-6c8f804e6046.png)

1.0 fixing (109 mb):
- Not tested (file is bigger than the original)

**Comment by afonsobspinto** [comment]
Conditions of the test:
- 10 objects per canvas
- Neuron RIH_RIH (heavist in the original files)

Original file (367 mb per canvas):
- ~5 fps
![image](https://user-images.githubusercontent.com/19196034/131525739-ecf11e9b-ffcb-4605-8206-216d833f9379.png)

0.1 fixing (40mb per canvas):
- 30 fps
![image](https://user-images.githubusercontent.com/19196034/131538460-b22c9179-5bf9-4d55-946b-3290bff36839.png)

0.05 fixing (16 mb per canvas):
- 60 fps
![image](https://user-images.githubusercontent.com/19196034/131538301-59a1de45-4f69-4327-b768-eb96d43760b5.png)

**Comment by afonsobspinto** [comment]
Conditions of the test:
- 20 objects per canvas
- Neuron RIH_RIH (heavist in the original files)

Original file (734 mb per canvas):
- Not tested (previous test was already bad)

0.1 fixing (80mb per canvas):
- 15 fps
![image](https://user-images.githubusercontent.com/19196034/131539849-0a577787-00cd-43bd-a876-51bcfc63900c.png)

0.05 fixing (32 mb per canvas):
- 30 fps
![image](https://user-images.githubusercontent.com/19196034/131539970-6cd362e6-692f-44e5-8019-084202804399.png)

**Comment by afonsobspinto** [comment]
Conditions of the test:
- 1 object per canvas
- Neuron RIH_RIH (heavist in the original files)
- **Using .gltf files (not .obj)**


Original file (23.2 mb per canvas, compressed):
- ~60 fps
![image](https://user-images.githubusercontent.com/19196034/131547706-f13f4588-1701-4eab-bed3-2f5e2a107357.png)
0.1 fixing (1.8mb per canvas, compressed):
- ~60 fps
![image](https://user-images.githubusercontent.com/19196034/131546991-c485d745-5bb2-405a-827e-c96792f52602.png)

0.05 fixing (0.8 mb per canvas, compressed):
- 60 fps
![image](https://user-images.githubusercontent.com/19196034/131548328-0503f079-4fa5-4209-a4c7-c5e2174efc66.png)

____________________________________________________________________________________________________________


Conditions of the test:
- 10 objects per canvas
- Neuron RIH_RIH (heavist in the original files)
- **Using .gltf files (not .obj)**


Original file (232 mb per canvas, compressed):
- ~10 fps
![image](https://user-images.githubusercontent.com/19196034/131547145-5fe74ee7-8bf6-476c-bf0d-d3e165dd0119.png)

0.1 fixing (18mb per canvas, compressed):
- ~60 fps
![image](https://user-images.githubusercontent.com/19196034/131546991-c485d745-5bb2-405a-827e-c96792f52602.png)

0.05 fixing (8 mb per canvas, compressed):
- 60 fps
![image](https://user-images.githubusercontent.com/19196034/131546678-6b54e244-a4f6-4f2b-adec-d52c0fa98f3b.png)

____________________________________________________________________________________________________________

Conditions of the test:
- 20 objects per canvas
- Neuron RIH_RIH (heavist in the original files)
- **Using .gltf files (not .obj)**


Original file (466 mb per canvas, compressed):
- ~10 fps
![image](https://user-images.githubusercontent.com/19196034/131545202-7f3b2d9c-afea-43b5-be52-770ade378eea.png)

0.1 fixing (36mb per canvas, compressed):
- ~35 fps
![image](https://user-images.githubusercontent.com/19196034/131545570-95589da6-0f0c-49ad-bd82-ce30404425fc.png)

0.05 fixing (16 mb per canvas, compressed):
- 60 fps
![image](https://user-images.githubusercontent.com/19196034/131545668-37897a62-bf3c-43c6-a7be-9cfc06d1b7a5.png)

**Comment by afonsobspinto** [comment]
Summary
The main goal of the experiments was to see how many objects we could show simultaneously.
The experiments were done using the heaviest neuron file (RIH) I had access to.
The following table shows information using the _draco.gltf version of the RIH neuron (converted from the .obj file yale provided us - for context: it is an open task for Yale to convert the .obj files into .gltf)

![image](https://user-images.githubusercontent.com/19196034/131684225-1ac55a8d-bf82-42aa-9866-e793e4e4191c.png)

In terms of conclusions there's not much I can conclude by myself.
It's clear that downscaling the meshes size contributes to the possibility of having more objects show simultaneously.
I would imagine that one of the things we want to show with these experiments is the level of detail / how accurate the objects will look for each of the scales/fixings Yale provided. There's a couple of screenshots posted above for that purpose.

Again I think is worth mentioning that the tests were done with the heaviest neuron file, so it's a kind of worst-case scenario test. In general, we should be able to show a couple more objects than the ones shown in the table

Another note is that the tests were made using the current Geppetto-Meta Canvas, but there's an open PR to update it from an infinite loop rendering to rendering on-demand.
It shouldn't affect the fps values but rather improve the CPU usage.
