### ISSUE TITLE
Data roadmap

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#158]
Data roadmap:

- [ ] data conversion to draco
- [x] folder structure readiness for the ingestion in dropbox
- [x] complete dataset uploaded
  - [x] all neurons
  - [x] all contacts
  - [x] all synapses
  - [x] all csv
